sudo: required
services:
  - docker

language: python
python:
  - "3.6"

before_install:
  - docker-compose build
  - docker-compose up -d
  - docker ps -a

before_script:
  - sleep 15

script:
  - pip install -r requirements.txt
  - pytest tests/test.py
  - pytest tests/test_match.py
  - pytest tests/test_chat.py

after_failure:
  - docker ps -a
  - docker-compose logs gateway

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose push gateway webapp
