sudo: required
services:
  - docker

language: python
python:
  - "3.6"

script:
  - echo "No tests yet"

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose build
  - docker-compose push gateway webapp