sudo: required
services:
- docker
- postgresql
language: python
python:
- '3.6'
before_install:
- docker pull capaths/gameswebapp
- docker pull capaths/gamesgateway
- docker-compose build
- docker-compose up -d
- docker ps -a
before_script:
- sleep 15
- docker-compose logs webapp
- docker-compose logs gateway
- docker-compose logs access
- docker-compose logs player
- docker-compose logs match
- docker-compose logs chat
- docker-compose logs ticket
script:
- pip install -r requirements.txt
- pytest tests/test.py
- pytest tests/test_match.py
- pytest tests/test_chat.py
- pytest tests/test_sqli.py
after_failure:
- docker ps -a
- docker-compose logs gateway
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker-compose push gateway webapp

after_deploy:
- docker pull owasp/zap2docker-weekly
- docker run --name owasp-gateway -t owasp/zap2docker-weekly zap-full-scan.py -t http://flaguesser.herokuapp.com/ -ja



deploy:
  provider: script
  script: bash docker_push
env:
  global:
    secure: nXCZLwlgb5wJcmbD/DxT2DvMK9ICeK7ftwx5RP22cl79EdZKaNEwEpfeX18Lx+sfUTH57zN5GC4btrDirJthzYiZjGNxqRaZ+z48ms7GMKxofUOlPvgE1tP844sHiAW1J4ndqw2qRmWQ3O7hNKAbEJH04c+DTiJ2HZ0bbNbLJIWAx2fszps9m7JO0imiDI8iqaljV2ZLaAgoKLlebgGKcYjsF44R4dphHmjPZDNBtuIe1BH+/tfvPuTUqEPgdnGEUqdPO/4QAV1NXDaYJM7YJOgS1EXPBMTJ8cB80oMHlQSx9lbDh5K6BOIMww0dEM/FwvI3mE9ZqIL4HJSZL8k5vO/T2d0CrtM/1qC0Li3MFQl/negZtVkJgBrKfkYC/uypf1+ZYE40ys9ky30R/6Z/lVMuYNEeIG8+e0agDIcNZENOiONfVB1gpC5jQVGEmKAI052UlusLQRDHEObQrPDQhzeD18hekCbko619cxRqJEadtxMHZGGp9w6BnCdTEZxa047MUYkT+NvrAFLB5ET5z90WwhpsWI++j0/tpIF12qqcnTczQZ/n1WxNIWLxDBMq95lC9srzb1I0RCGHzg7NtIC34cuqlnvWULjEJ5YB16hhzRNJN1r4lS5nev2rsJjLsyqaDZghPkA10Z2sLWtntQIjaLNoavezMCMr83uSv38=
