sudo: required
services:
- docker
- postgresql
language: python
python:
- '3.6'
before_install:
- docker-compose build
- docker-compose up -d
- docker ps -a
before_script:
- sleep 15
- docker-compose logs gateway
script:
- pip install -r requirements.txt
- pytest tests/test.py
- pytest tests/test_match.py
- pytest tests/test_chat.py
after_failure:
- docker ps -a
- docker-compose logs gateway
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker-compose push gateway webapp
- docker pull owasp/zap2docker-weekly
- docker run --name owasp-gateway --link gateway -t owasp/zap2docker-weekly zap-full-scan.py -t http://localhost:8000
- docker run --name owasp-webapp --link webapp -t owasp/zap2docker-weekly zap-full-scan.py -t http://localhost:8080
deploy:
  provider: script
  script: bash docker_push
env:
  global:
    secure: ZsnrbARCLtVX2tA85mnkXAJdCIJiU96oi0Z+j7GU1E8KOzk8WjG2mYMztW/sJmgJaGqb5BnxaVojMj3ulBLA1fW/BxPQi/Kkl0pZvS7pBuBrnMYCdXTsJUO2Qn60Z4Grh7O+CEsIK7xQBRh5ejhYlVZASXUBHjY/xYBtq11AC/e6pIlYCy9/M114tHNOVzXlHwW+ihwx0hrwatwKBCuAUJqN9ACPP7bbEqW1xwGU3+wE4gMRqcxepTuRgkVtzF21s9Zzo136z38AZd35NxgIQf14b3RWsBVS2NWczBQiOrYyiipkrAKLPH2l0gFiLuAnW0i12lN/eBd2kjvBzXsBAldm6aDVdNA4jOH6d+QNa9FN1Lcm5gpNsjrQ0vdryKJo6FDK5YrArPDd9FlWvaHobTX184MpCXMc4N3i3uCOmLfosXNfTksR+nJhZ9WQM4czP766RbpIf/Dtb8UvRe7Zieb8CgwMKVrDIWdMEnJmXN5/eSAGqE69fCNKN1xrZBYewLQOa4DDn9XY1OneZEHnOBvpubxR6JdLdmxrzGYWb6LtBq/imP37EnKUqSoku81dfKqiWmmLz2cjXeKhBAzzMOXtpnZ1is75U8QhhKFT9ASD4QB8ZrzNShttDq5QkTGGUctZaEC4YOaqfZ4y4qFZ2a5+6XRSHU/br/nBGIeG8/A=
