#!/usr/bin/env bash

WORKERS=( "flaguesser-access" "flaguesser-chat" "flaguesser-match" "flaguesser-player" )
DOCKER_IMGS=( "capaths/gamesaccess" "capaths/gameschat" "capaths/gamesmatch" "161905/gamesplayer" )

for i in "${!WORKERS[@]}"
do
    WORKER_NAME=${WORKERS[$i]}
    DOCKER_TAG=${DOCKER_IMGS[$i]}

    echo "Logging in to ${WORKER_NAME}"
    echo "${HEROKU_API_KEY}" | docker login -u "_" --password-stdin registry.heroku.com/${WORKER_NAME}/worker
    if [[ $? == 0 ]]; then
        docker tag ${DOCKER_TAG} registry.heroku.com/${WORKER_NAME}/worker

        echo "Pushing ${WORKER_NAME}"
        docker push registry.heroku.com/${WORKER_NAME}/worker

        echo "Releasing ${WORKER_NAME}"
        heroku login
        heroku container:release worker -a ${WORKER_NAME}
    fi
done

echo "${HEROKU_API_KEY}" | docker login -u "_" --password-stdin registry.heroku.com/flaguesser/web

if [[ $? == 0 ]]; then
    docker tag capaths/gamesgateway registry.heroku.com/flaguesser/web
    docker push registry.heroku.com/flaguesser/web
    heroku container:release web -a flaguesser
fi
